// components/entry-card.tsx
import Link from "next/link";
import { Heart, Pencil } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import type { CoffeeEntry } from "@/lib/mock-data";

export function EntryCard({ entry }: { entry: CoffeeEntry }) {
  return (
    <Card className="space-y-3">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <CardTitle className="text-lg">
              <Link href={`/entries/${entry.id}`} className="hover:underline">
                {entry.title}
              </Link>
            </CardTitle>
            {entry.favorite && (
              <Heart size={15} className="shrink-0 fill-amber-600 text-amber-600" aria-label="Top sip" />
            )}
          </div>
          <CardDescription>
            {entry.cafe} • {entry.roaster} • {entry.location}
          </CardDescription>
          <p className="mt-0.5 text-xs text-stone-400">{entry.dateConsumed}</p>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <Badge>Sip Score {entry.rating}/10</Badge>
          <Link
            href={`/entries/${entry.id}/edit`}
            aria-label="Edit entry"
            className="rounded p-1 text-stone-400 hover:text-stone-700"
          >
            <Pencil size={14} />
          </Link>
        </div>
      </div>
      <p className="text-sm text-stone-700">{entry.reviewBody}</p>
      <div className="flex flex-wrap gap-2">
        {entry.tastingNotes.map((note) => (
          <Badge key={note} className="bg-amber-50 border-amber-200 text-amber-900">
            {note}
          </Badge>
        ))}
      </div>
    </Card>
  );
}

// nuxt/components/EntryCard.vue
<script setup lang="ts">
import type { CoffeeEntry } from "~/utils/types";

defineProps<{
  entry: CoffeeEntry;
}>();
</script>

<template>
  <UCard>
    <div class="space-y-3">
      <div class="flex items-start justify-between gap-4">
        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-2">
            <h3 class="text-lg font-semibold text-stone-900">
              <NuxtLink :to="`/entries/${entry.id}`" class="hover:underline">
                {{ entry.title }}
              </NuxtLink>
            </h3>
            <UIcon
              v-if="entry.favorite"
              name="i-lucide-heart"
              class="size-4 shrink-0 text-amber-600"
              aria-label="Top sip"
            />
          </div>
          <p class="text-sm text-stone-500">
            {{ entry.cafe }} &bull; {{ entry.roaster }} &bull; {{ entry.location }}
          </p>
          <p class="mt-0.5 text-xs text-stone-400">{{ entry.dateConsumed }}</p>
        </div>
        <div class="flex shrink-0 items-center gap-2">
          <UBadge color="primary" variant="subtle">Sip Score {{ entry.rating }}/10</UBadge>
          <NuxtLink
            :to="`/entries/${entry.id}/edit`"
            aria-label="Edit entry"
            class="rounded p-1 text-stone-400 hover:text-stone-700"
          >
            <UIcon name="i-lucide-pencil" class="size-3.5" />
          </NuxtLink>
        </div>
      </div>

      <p class="text-sm text-stone-700">{{ entry.reviewBody }}</p>

      <div class="flex flex-wrap gap-2">
        <UBadge
          v-for="note in entry.tastingNotes"
          :key="note"
          color="warning"
          variant="subtle"
        >
          {{ note }}
        </UBadge>
      </div>
    </div>
  </UCard>
</template>
