// app/pages/lists/[id].vue
<script setup lang="ts">
import { lists as allLists, coffeeEntries } from "~/composables/useMockData";

const route = useRoute();
const id = route.params.id as string;
const list = allLists.find((l) => l.id === id);

type ListsDetailContent = {
  backLabel: string;
  empty: string;
  labels: {
    public: string;
    private: string;
    sipSingular: string;
    sipPlural: string;
  };
};

const fallbackContent: ListsDetailContent = {
  backLabel: "Back to Lists",
  empty: "This list has no entries yet.",
  labels: {
    public: "Public",
    private: "Private",
    sipSingular: "sip",
    sipPlural: "sips",
  },
};

const { data: listsDetailData } = await useAsyncData("lists-detail-content", () =>
  queryCollection("content").path("/lists/detail").first()
);

const content = computed(() => (listsDetailData.value as ListsDetailContent | null) ?? fallbackContent);

if (!list) {
  throw createError({ statusCode: 404, statusMessage: "List not found" });
}

const entries = coffeeEntries.filter((e) => list.entryIds.includes(e.id));
</script>

<template>
  <div class="space-y-6">
    <div>
      <NuxtLink to="/lists" class="text-sm text-stone-500 hover:text-stone-800">
        ← {{ content.backLabel }}
      </NuxtLink>
    </div>

    <UCard>
      <div class="space-y-2">
        <div class="flex items-start justify-between gap-4">
          <h1 class="font-semibold text-stone-900">{{ list.title }}</h1>
          <span class="flex shrink-0 items-center gap-1 text-xs text-stone-500">
            <UIcon :name="list.isPublic ? 'i-lucide-globe' : 'i-lucide-lock'" class="size-3" />
            {{ list.isPublic ? content.labels.public : content.labels.private }}
          </span>
        </div>
        <p v-if="list.description" class="text-sm text-stone-500">{{ list.description }}</p>
        <p class="text-xs text-stone-400">
          {{ entries.length }}
          {{ entries.length === 1 ? content.labels.sipSingular : content.labels.sipPlural }}
        </p>
      </div>
    </UCard>

    <div v-if="entries.length" class="space-y-4">
      <EntryCard v-for="entry in entries" :key="entry.id" :entry="entry" />
    </div>
    <p v-else class="text-stone-600">{{ content.empty }}</p>
  </div>
</template>

// app/lists/[id]/page.tsx
import Link from "next/link";
import { notFound } from "next/navigation";
import { Globe, Lock } from "lucide-react";

import { AppHeader } from "@/components/app-header";
import { EntryCard } from "@/components/entry-card";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { coffeeEntries, lists } from "@/lib/mock-data";

export default async function ListDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const list = lists.find((l) => l.id === id);

  if (!list) {
    notFound();
  }

  const entries = coffeeEntries.filter((e) => list.entryIds.includes(e.id));

  return (
    <div className="min-h-screen">
      <AppHeader activePath="/lists" />
      <main className="mx-auto w-full max-w-4xl space-y-6 px-5 py-8">
        <div>
          <Link href="/lists" className="text-sm text-stone-500 hover:text-stone-800">
            ← Back to Lists
          </Link>
        </div>

        <Card className="space-y-2">
          <div className="flex items-start justify-between gap-4">
            <CardTitle>{list.title}</CardTitle>
            <span className="flex shrink-0 items-center gap-1 text-xs text-stone-500">
              {list.isPublic ? <Globe size={12} /> : <Lock size={12} />}
              {list.isPublic ? "Public" : "Private"}
            </span>
          </div>
          {list.description && <CardDescription>{list.description}</CardDescription>}
          <p className="text-xs text-stone-400">
            {entries.length} sip{entries.length !== 1 ? "s" : ""}
          </p>
        </Card>

        {entries.length ? (
          <div className="space-y-4">
            {entries.map((entry) => (
              <EntryCard key={entry.id} entry={entry} />
            ))}
          </div>
        ) : (
          <p className="text-stone-600">This list has no entries yet.</p>
        )}
      </main>
    </div>
  );
}
