// components/lists-manager.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { Globe, Lock, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { List } from "@/lib/mock-data";

let nextId = 100;

export function ListsManager({
  initialLists,
  userId,
}: {
  initialLists: List[];
  userId: string;
}) {
  const [lists, setLists] = useState<List[]>(initialLists);
  const [showForm, setShowForm] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [isPublic, setIsPublic] = useState(true);

  function createList() {
    if (!title.trim()) return;
    const newList: List = {
      id: `l${nextId++}`,
      userId,
      title: title.trim(),
      description: description.trim(),
      isPublic,
      entryIds: [],
    };
    setLists((prev) => [newList, ...prev]);
    setTitle("");
    setDescription("");
    setIsPublic(true);
    setShowForm(false);
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold tracking-tight">My Lists</h1>
        <Button variant="outline" onClick={() => setShowForm((v) => !v)}>
          <Plus size={15} className="mr-1.5" />
          {showForm ? "Cancel" : "New List"}
        </Button>
      </div>

      {showForm && (
        <Card className="space-y-3">
          <CardTitle className="text-base">Create a new list</CardTitle>
          <Input
            placeholder="List name"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <Textarea
            placeholder="Description (optional)"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
          <label className="flex items-center gap-2 text-sm text-stone-600">
            <input
              type="checkbox"
              checked={isPublic}
              onChange={(e) => setIsPublic(e.target.checked)}
            />
            Make this list public
          </label>
          <Button onClick={createList} disabled={!title.trim()}>
            Create List
          </Button>
        </Card>
      )}

      {lists.length ? (
        <div className="space-y-3">
          {lists.map((list) => (
            <Link key={list.id} href={`/lists/${list.id}`} className="block">
              <Card className="space-y-1 transition hover:border-stone-300">
                <div className="flex items-start justify-between gap-4">
                  <CardTitle>{list.title}</CardTitle>
                  <span className="flex shrink-0 items-center gap-1 text-xs text-stone-500">
                    {list.isPublic ? <Globe size={12} /> : <Lock size={12} />}
                    {list.isPublic ? "Public" : "Private"}
                  </span>
                </div>
                {list.description && (
                  <CardDescription>{list.description}</CardDescription>
                )}
                <p className="text-xs text-stone-400">
                  {list.entryIds.length} sip{list.entryIds.length !== 1 ? "s" : ""}
                </p>
              </Card>
            </Link>
          ))}
        </div>
      ) : (
        <p className="text-stone-600">No lists yet. Create one to organise your sips.</p>
      )}
    </div>
  );
}

// app/components/ListsManager.vue
<script setup lang="ts">
import type { List } from "~/utils/types";

const props = defineProps<{
  initialLists: List[];
  userId: string;
  copy?: {
    title: string;
    actions: { create: string; cancel: string };
    form: {
      title: string;
      listName: string;
      description: string;
      makePublic: string;
      submit: string;
    };
    empty: string;
    labels: {
      public: string;
      private: string;
      sipSingular: string;
      sipPlural: string;
    };
  };
}>();

const copy = computed(() =>
  props.copy ?? {
    title: "My Lists",
    actions: { create: "New List", cancel: "Cancel" },
    form: {
      title: "Create a new list",
      listName: "List name",
      description: "Description (optional)",
      makePublic: "Make this list public",
      submit: "Create List",
    },
    empty: "No lists yet. Create one to organise your sips.",
    labels: {
      public: "Public",
      private: "Private",
      sipSingular: "sip",
      sipPlural: "sips",
    },
  }
);

const lists = ref<List[]>([...props.initialLists]);
const showForm = ref(false);
const title = ref("");
const description = ref("");
const isPublic = ref(true);

let nextId = 100;

function createList() {
  if (!title.value.trim()) return;
  const newList: List = {
    id: `l${nextId++}`,
    userId: props.userId,
    title: title.value.trim(),
    description: description.value.trim(),
    isPublic: isPublic.value,
    entryIds: [],
  };
  lists.value.unshift(newList);
  title.value = "";
  description.value = "";
  isPublic.value = true;
  showForm.value = false;
}
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-semibold tracking-tight">{{ copy.title }}</h1>
      <UButton variant="outline" @click="showForm = !showForm">
        <UIcon name="i-lucide-plus" class="mr-1.5 size-4" />
        {{ showForm ? copy.actions.cancel : copy.actions.create }}
      </UButton>
    </div>

    <UCard v-if="showForm">
      <div class="space-y-3">
        <h2 class="text-base font-semibold">{{ copy.form.title }}</h2>
        <UInput v-model="title" :placeholder="copy.form.listName" />
        <UTextarea v-model="description" :placeholder="copy.form.description" />
        <label class="flex items-center gap-2 text-sm text-stone-600">
          <input v-model="isPublic" type="checkbox" />
          {{ copy.form.makePublic }}
        </label>
        <UButton :disabled="!title.trim()" @click="createList">{{ copy.form.submit }}</UButton>
      </div>
    </UCard>

    <div v-if="lists.length" class="space-y-3">
      <NuxtLink v-for="list in lists" :key="list.id" :to="`/lists/${list.id}`" class="block">
        <UCard class="transition hover:border-stone-300">
          <div class="space-y-1">
            <div class="flex items-start justify-between gap-4">
              <h3 class="font-semibold text-stone-900">{{ list.title }}</h3>
              <span class="flex shrink-0 items-center gap-1 text-xs text-stone-500">
                <UIcon :name="list.isPublic ? 'i-lucide-globe' : 'i-lucide-lock'" class="size-3" />
                {{ list.isPublic ? copy.labels.public : copy.labels.private }}
              </span>
            </div>
            <p v-if="list.description" class="text-sm text-stone-500">{{ list.description }}</p>
            <p class="text-xs text-stone-400">
              {{ list.entryIds.length }}
              {{ list.entryIds.length === 1 ? copy.labels.sipSingular : copy.labels.sipPlural }}
            </p>
          </div>
        </UCard>
      </NuxtLink>
    </div>
    <p v-else class="text-stone-600">{{ copy.empty }}</p>
  </div>
</template>
