// nuxt/pages/saved-sips.vue
<script setup lang="ts">
import { demoUserId, coffeeEntries } from "~/composables/useMockData";

const savedSips = coffeeEntries.filter(
  (entry) => entry.userId === demoUserId && entry.wouldOrderAgain
);

type SavedSipsContent = {
  title: string;
  empty: string;
};

const fallbackContent: SavedSipsContent = {
  title: "Saved Sips",
  empty: "No saved sips yet.",
};

const { data: savedSipsData } = await useAsyncData("saved-sips-content", () =>
  queryCollection("content").path("/saved-sips/index").first()
);

const content = computed(() => (savedSipsData.value as SavedSipsContent | null) ?? fallbackContent);
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold tracking-tight">
      {{ content.title }}
      <span v-if="savedSips.length" class="ml-2 text-base font-normal text-stone-500">
        ({{ savedSips.length }})
      </span>
    </h1>
    <template v-if="savedSips.length">
      <EntryCard v-for="sip in savedSips" :key="sip.id" :entry="sip" />
    </template>
    <p v-else class="text-stone-600">{{ content.empty }}</p>
  </div>
</template>

// app/saved-sips/page.tsx
import { AppHeader } from "@/components/app-header";
import { EntryCard } from "@/components/entry-card";
import { coffeeEntries, demoUserId } from "@/lib/mock-data";

export default function SavedSipsPage() {
  const savedSips = coffeeEntries.filter(
    (entry) => entry.userId === demoUserId && entry.wouldOrderAgain
  );

  return (
    <div className="min-h-screen">
      <AppHeader activePath="/saved-sips" />
      <main className="mx-auto w-full max-w-4xl space-y-4 px-5 py-8">
        <h1 className="text-2xl font-semibold tracking-tight">
          Saved Sips{savedSips.length > 0 && (
            <span className="ml-2 text-base font-normal text-stone-500">({savedSips.length})</span>
          )}
        </h1>
        {savedSips.length ? (
          savedSips.map((sip) => <EntryCard key={sip.id} entry={sip} />)
        ) : (
          <p className="text-stone-600">No saved sips yet.</p>
        )}
      </main>
    </div>
  );
}
