// app/entries/[id]/edit/page.tsx
import Link from "next/link";
import { notFound } from "next/navigation";

import { AddEntryForm } from "@/components/add-entry-form";
import { AppHeader } from "@/components/app-header";
import { Card, CardTitle } from "@/components/ui/card";
import { coffeeEntries } from "@/lib/mock-data";

export default async function EditEntryPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const entry = coffeeEntries.find((item) => item.id === id);

  if (!entry) {
    notFound();
  }

  return (
    <div className="min-h-screen">
      <AppHeader activePath="/diary" />
      <main className="mx-auto w-full max-w-3xl px-5 py-8">
        <div className="mb-4">
          <Link href={`/entries/${id}`} className="text-sm text-stone-500 hover:text-stone-800">
            ← Back to entry
          </Link>
        </div>
        <Card className="space-y-4">
          <CardTitle>Edit Sip</CardTitle>
          <AddEntryForm
            initialValues={{
              title: entry.title,
              drinkType: entry.drinkType,
              cafe: entry.cafe,
              roaster: entry.roaster,
              rating: String(entry.rating),
              reviewBody: entry.reviewBody,
              dateConsumed: entry.dateConsumed,
              wouldOrderAgain: entry.wouldOrderAgain,
              visibility: entry.visibility,
              origin: entry.origin,
              roastLevel: entry.roastLevel as never,
              brewMethod: entry.brewMethod as never,
              tastingNotes: entry.tastingNotes,
            }}
          />
        </Card>
      </main>
    </div>
  );
}

// app/pages/entries/[id]/edit.vue
<script setup lang="ts">
import { coffeeEntries } from "~/composables/useMockData";

const route = useRoute();
const id = route.params.id as string;
const entry = coffeeEntries.find((item) => item.id === id);

type EntryEditContent = {
  backLabel: string;
  title: string;
};

const fallbackContent: EntryEditContent = {
  backLabel: "Back to entry",
  title: "Edit Sip",
};

const { data: entryEditData } = await useAsyncData("entry-edit-content", () =>
  queryCollection("content").where("stem", "=", "entries/edit").first()
);

const content = computed(() => (entryEditData.value as EntryEditContent | null) ?? fallbackContent);

if (!entry) {
  throw createError({ statusCode: 404, statusMessage: "Entry not found" });
}

const initialValues = {
  title: entry.title,
  drinkType: entry.drinkType,
  cafe: entry.cafe,
  roaster: entry.roaster,
  rating: String(entry.rating),
  reviewBody: entry.reviewBody,
  dateConsumed: entry.dateConsumed,
  wouldOrderAgain: entry.wouldOrderAgain,
  visibility: entry.visibility,
  origin: entry.origin,
  roastLevel: entry.roastLevel,
  brewMethod: entry.brewMethod,
  tastingNotes: entry.tastingNotes,
};
</script>

<template>
  <div>
    <div class="mb-4">
      <NuxtLink :to="`/entries/${id}`" class="text-sm text-stone-500 hover:text-stone-800">
        ← {{ content.backLabel }}
      </NuxtLink>
    </div>
    <UCard>
      <div class="space-y-4">
        <h1 class="font-semibold text-stone-900">{{ content.title }}</h1>
        <AddEntryForm :initial-values="initialValues" />
      </div>
    </UCard>
  </div>
</template>
