// app/diary/page.tsx
import { AppHeader } from "@/components/app-header";
import { EntryCard } from "@/components/entry-card";
import { coffeeEntries, demoUserId } from "@/lib/mock-data";

export default function DiaryPage() {
  const entries = coffeeEntries
    .filter((entry) => entry.userId === demoUserId)
    .sort((a, b) => b.dateConsumed.localeCompare(a.dateConsumed));

  return (
    <div className="min-h-screen">
      <AppHeader activePath="/diary" />
      <main className="mx-auto w-full max-w-4xl px-5 py-8">
        <h1 className="mb-5 text-2xl font-semibold tracking-tight">Diary</h1>
        <div className="space-y-4">
          {entries.length ? (
            entries.map((entry) => <EntryCard key={entry.id} entry={entry} />)
          ) : (
            <div className="space-y-2 rounded-xl border border-dashed border-stone-300 bg-white p-6">
              <p className="font-medium text-stone-800">No sips logged yet.</p>
              <p className="text-sm text-stone-600">Start your Sip Log with your first great cup.</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

// app/pages/diary.vue
<script setup lang="ts">
const { userEntries } = useMockData();
const entries = [...userEntries].sort((a, b) => b.dateConsumed.localeCompare(a.dateConsumed));

type DiaryContent = {
  title: string;
  empty: { title: string; body: string };
};

const fallbackContent: DiaryContent = {
  title: "Sip Log",
  empty: {
    title: "No sips logged yet.",
    body: "Start your Sip Log with your first great cup.",
  },
};

const { data: diaryData } = await useAsyncData("diary-content", () =>
  queryCollection("content").where("stem", "=", "diary/index").first()
);

const content = computed(() => (diaryData.value as DiaryContent | null) ?? fallbackContent);
</script>

<template>
  <div>
    <h1 class="mb-5 text-2xl font-semibold tracking-tight">{{ content.title }}</h1>
    <div class="space-y-4">
      <template v-if="entries.length">
        <EntryCard v-for="entry in entries" :key="entry.id" :entry="entry" />
      </template>
      <div v-else class="space-y-2 rounded-xl border border-dashed border-stone-300 bg-white p-6">
        <p class="font-medium text-stone-800">{{ content.empty.title }}</p>
        <p class="text-sm text-stone-600">{{ content.empty.body }}</p>
      </div>
    </div>
  </div>
</template>
