// app/components/ProfileForm.vue
<script setup lang="ts">
import type { AppUser, CoffeeEntry } from "~/utils/types";

const props = defineProps<{
  user: AppUser;
  entries: CoffeeEntry[];
  copy?: {
    tasteIdentityTitle: string;
    favoriteDrinkLabel: string;
    actions: { edit: string; save: string; cancel: string };
    placeholders: {
      displayName: string;
      homeCity: string;
      favoriteDrink: string;
      bio: string;
    };
  };
}>();

const copy = computed(() =>
  props.copy ?? {
    tasteIdentityTitle: "Taste identity",
    favoriteDrinkLabel: "Favourite drink",
    actions: { edit: "Edit", save: "Save", cancel: "Cancel" },
    placeholders: {
      displayName: "Display name",
      homeCity: "Home city",
      favoriteDrink: "Favourite drink",
      bio: "Bio",
    },
  }
);

const editing = ref(false);
const user = ref({ ...props.user });
const draft = ref({ ...props.user });

function startEdit() {
  draft.value = { ...user.value };
  editing.value = true;
}

function saveEdit() {
  user.value = { ...draft.value };
  editing.value = false;
  // TODO: call server API to persist profile
}

function cancelEdit() {
  draft.value = { ...user.value };
  editing.value = false;
}
</script>

<template>
  <div class="space-y-4">
    <UCard>
      <div class="space-y-3">
        <div class="flex items-start justify-between gap-4">
          <div>
            <h2 class="font-semibold text-stone-900">{{ user.name }}</h2>
            <p class="text-sm text-stone-500">{{ user.handle }} &bull; {{ user.homeCity }}</p>
            <p v-if="!editing" class="mt-1.5 text-sm text-stone-700">{{ user.bio }}</p>
          </div>
          <UButton v-if="!editing" variant="outline" @click="startEdit">
            <UIcon name="i-lucide-pencil" class="mr-1.5 size-3.5" />
            {{ copy.actions.edit }}
          </UButton>
        </div>

        <div v-if="editing" class="space-y-3 border-t border-stone-100 pt-3">
          <div class="grid gap-3 sm:grid-cols-2">
            <UInput v-model="draft.name" :placeholder="copy.placeholders.displayName" />
            <UInput v-model="draft.homeCity" :placeholder="copy.placeholders.homeCity" />
            <UInput v-model="draft.favoriteDrink" :placeholder="copy.placeholders.favoriteDrink" />
          </div>
          <UTextarea v-model="draft.bio" :placeholder="copy.placeholders.bio" />
          <div class="flex gap-2">
            <UButton @click="saveEdit">{{ copy.actions.save }}</UButton>
            <UButton variant="ghost" @click="cancelEdit">{{ copy.actions.cancel }}</UButton>
          </div>
        </div>
      </div>
    </UCard>

    <UCard>
      <div class="space-y-2">
        <h3 class="font-semibold text-stone-900">{{ copy.tasteIdentityTitle }}</h3>
        <p class="text-sm text-stone-500">
          {{ entries.length }} sip{{ entries.length !== 1 ? "s" : "" }} &bull;
          {{ entries.filter((e) => e.favorite).length }} top pick{{
            entries.filter((e) => e.favorite).length !== 1 ? "s" : ""
          }}
        </p>
        <p v-if="user.favoriteDrink" class="text-sm text-stone-700">
          {{ copy.favoriteDrinkLabel }}: {{ user.favoriteDrink }}
        </p>
      </div>
    </UCard>
  </div>
</template>

// components/profile-form.tsx
"use client";

import { useState } from "react";
import { Pencil } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { AppUser, CoffeeEntry } from "@/lib/mock-data";

export function ProfileForm({
  user: initialUser,
  entries,
}: {
  user: AppUser;
  entries: CoffeeEntry[];
}) {
  const [editing, setEditing] = useState(false);
  const [user, setUser] = useState(initialUser);
  const [draft, setDraft] = useState(initialUser);

  function startEdit() {
    setDraft(user);
    setEditing(true);
  }

  function saveEdit() {
    setUser(draft);
    setEditing(false);
  }

  function cancelEdit() {
    setDraft(user);
    setEditing(false);
  }

  return (
    <div className="space-y-4">
      <Card className="space-y-3">
        <div className="flex items-start justify-between gap-4">
          <div>
            <CardTitle>{user.name}</CardTitle>
            <CardDescription>
              {user.handle} • {user.homeCity}
            </CardDescription>
            {!editing && <p className="mt-1.5 text-sm text-stone-700">{user.bio}</p>}
          </div>
          {!editing && (
            <Button variant="outline" onClick={startEdit}>
              <Pencil size={14} className="mr-1.5" />
              Edit
            </Button>
          )}
        </div>

        {editing && (
          <div className="space-y-3 border-t border-stone-100 pt-3">
            <div className="grid gap-3 sm:grid-cols-2">
              <Input
                placeholder="Display name"
                value={draft.name}
                onChange={(e) => setDraft((prev) => ({ ...prev, name: e.target.value }))}
              />
              <Input
                placeholder="Home city"
                value={draft.homeCity}
                onChange={(e) => setDraft((prev) => ({ ...prev, homeCity: e.target.value }))}
              />
              <Input
                placeholder="Favourite drink"
                value={draft.favoriteDrink}
                onChange={(e) => setDraft((prev) => ({ ...prev, favoriteDrink: e.target.value }))}
              />
            </div>
            <Textarea
              placeholder="Bio"
              value={draft.bio}
              onChange={(e) => setDraft((prev) => ({ ...prev, bio: e.target.value }))}
            />
            <div className="flex gap-2">
              <Button onClick={saveEdit}>Save</Button>
              <Button variant="ghost" onClick={cancelEdit}>Cancel</Button>
            </div>
          </div>
        )}
      </Card>

      <Card className="space-y-2">
        <CardTitle>Taste identity</CardTitle>
        <CardDescription>
          {entries.length} sip{entries.length !== 1 ? "s" : ""} •{" "}
          {entries.filter((e) => e.favorite).length} top pick
          {entries.filter((e) => e.favorite).length !== 1 ? "s" : ""}
        </CardDescription>
        {user.favoriteDrink && (
          <p className="text-sm text-stone-700">Favourite drink: {user.favoriteDrink}</p>
        )}
      </Card>
    </div>
  );
}
